aziontech/azion

- pkg/cmd/publish/publish.go
**WHAT**
Update Rules Engine was being called while Application ID is Blank.
> fix: add application id to conf before calling rules engine

- README.md
Syntax highlight from type sh is interpreting the azion-cli output as shell script, highlighting text between quotes and words like command, help and for
> docs: remove syntax highlight from help execution

- pkg/cmd/root/root.go
**WHAT**
Invert order of messages in root command.
**WHY**
[ENG-20529]
[ENG-20529]: https://aziontech.atlassian.net/browse/ENG-20529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-20529] chore: invert order of messages in rootcmd help

- pkg/api/domains/domains.go
- pkg/api/edge_applications/edge_applications.go
- pkg/api/edge_functions/edge_functions.go
- pkg/api/realtime_purge/realtime_purge.go
- pkg/cmd/edge_services/create/create.go
- pkg/cmd/edge_services/delete/delete.go
- pkg/cmd/edge_services/describe/describe.go
- pkg/cmd/edge_services/list/list.go
- pkg/cmd/edge_services/requests/request.go
- pkg/cmd/edge_services/resources/create/create.go
- pkg/cmd/edge_services/resources/delete/delete.go
- pkg/cmd/edge_services/resources/describe/describe.go
- pkg/cmd/edge_services/resources/list/list.go
- pkg/cmd/edge_services/resources/update/update.go
- pkg/cmd/edge_services/update/update.go
- utils/errors.go
- utils/helpers.go
**WHAT**
Azioncli sometimes would return an internal server error message, even though the process finished successfully. This was due to a timeout within our SDK. 
The solution was to provide our own timeout (currently 10 seconds) and, in case the timeout still happened, print a clarifying message to the user. 
**WHY**
[ENG-20839]
[ENG-20839]: https://aziontech.atlassian.net/browse/ENG-20839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ENG-20839] chore: in case of timeout, we provide a clarifying message

- pkg/cmd/edge_services/resources/list/list.go
**WHAT**
When calling `azioncli edge_services resources list <ID>` with the flag `--details`, CLI would return an error. 
**WHY**
[NO ISSUE]
> fix: change type to trigger in --details

- pkg/cmd/init/init.go
When some space between a directory name in destination directory of git clone, a error happen (status 129).
This PR add quotation marks to absolute path of destination directory  in git clone parameters
> Adding quotations marks to absolute path of destination directory 

- pkg/cmd/webapp/build/build.go
- pkg/cmd/webapp/init/init.go
- pkg/cmd/webapp/publish/publish.go
**WHAT**
Webapp examples were different from how you actually use them.
> fix: exemples showing correct command tree

- .github/workflows/deploy_prod.yml
- .goreleaser.yaml
- README.md
- pkg/cmd/webapp/init/init.go
- pkg/cmd/webapp/publish/publish.go
- utils/errors.go
**WHAT**
- adding goreleaser suport: azioncli is available as `homebrew`, `rpm`, `deb` and `apk` packages;
- azioncli can be downloaded through homebew, using: `brew install aziontech/tap/azioncli` (when pushed to master);
- removing unused error message.
> chore: add goreleaser support

- pkg/cmd/webapp/init/init.go
**WHAT**
When you used `azioncli webapp init` for the first time in your project, package.json file would be incorrectly indented.
> fix: correct indentation in package.json on first init

- messages/webapp/errors.go
- messages/webapp/messages.go
- pkg/cmd/webapp/build/build.go
- pkg/cmd/webapp/init/init.go
- pkg/cmd/webapp/publish/publish.go
**WHAT**
- Remove message saying that no cmd was found and thus no action will be taken. This message was confusing and made no sense.
> chore: remove 'command not specified' message

- Makefile
Before this change, the error message is:
/bin/bash: line 1: version: command not found
make: *** [Makefile:84: build] Error 127
After that:
Makefile:7: *** "No go binary found in
/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, please install go before continue".  Stop.
> chore: improve error message when go is not found

- messages/webapp/errors.go
- messages/webapp/messages.go
- pkg/cmd/webapp/build/build.go
- pkg/cmd/webapp/build/build_test.go
- pkg/cmd/webapp/webapp_test.go
**WHAT**
- Add interactive terminal input for AWS credentials;
- Webdev.env file is written after the process worked successfully. 
- Unit tests;
- Functional tests.
> feat: add interactive terminal input for AWS credentials

- messages/edge_applications/errors.go
- messages/edge_applications/messages.go
- pkg/cmd/edge_applications/build/build.go
- pkg/cmd/edge_applications/init/init.go
- pkg/cmd/edge_applications/publish/publish.go
- pkg/cmd/edge_applications/publish/publish_test.go
- pkg/contracts/contracts.go
- utils/helpers.go
**WHAT**
- Add cdn type to edge_application web application types. This is a very simple type with only an edge application and domain. 
- Update init, build and publish commands to verify if type is cdn before anything else, as the whole process is different.
> feat: add cdn type to edge_applications

- messages/edge_applications/errors.go
- messages/edge_applications/messages.go
- pkg/api/domains/domains.go
- pkg/api/edge_applications/edge_applications.go
- pkg/api/edge_functions/edge_functions.go
- pkg/cmd/edge_applications/delete/delete.go
- pkg/cmd/edge_applications/delete/delete_test.go
- pkg/cmd/edge_applications/delete/fixtures/azion.json
- pkg/cmd/edge_applications/update/update.go
- utils/helpers.go
**WHAT**
- Add `--cascade` flag to delete command (edge_applications); 
- Unit tests;
- Code refactoring.
Cascade delete:
This PR adds the following: deleting everything that it's created by the publish command. This deletion is based on the azion.json file, since it is also what we use in the publish command.
> feat: add cascade delete to edge_applications

- messages/edge_applications/messages.go
- pkg/cmd/edge_applications/update/update.go
**WHAT**
- Remove --active flag, because we can never change it;
- Update message to say Edge Application instead of Edge Function.
> chore: remove active flag from edge_applications update

- messages/domains/errors.go
- pkg/api/domains/domains.go
- pkg/cmd/domains/create/create.go
- pkg/cmd/domains/describe/describe.go
- pkg/cmd/domains/describe/describe_test.go
- pkg/cmd/domains/describe/fixtures/domain.json
**WHAT**
- Correct error returned when mandatory flags are not sent;
- Fix message to format json body into error;
- Change functions to domains;
- Check mandatory flags only if --in is not sent;
- Domains Describe now shows more fields;
- Remove unnecessary json fields in structure.
> chore: many small fixes to domain command tree

- go.mod
- go.sum
- messages/origins/errors.go
- messages/origins/messages.go
- pkg/api/edge_applications/edge_applications.go
- pkg/cmd/edge_applications/init/init.go
- pkg/cmd/origins/describe/describe.go
- pkg/cmd/origins/describe/describe_test.go
- pkg/cmd/origins/describe/fixtures/noorigins.json
- pkg/cmd/origins/describe/fixtures/origins.json
- pkg/cmd/origins/origins.go
- create command describe
- test unit
> Feat: create command describe

- .github/workflows/deploy_prod.yml
- .github/workflows/deploy_stage.yml
- .goreleaser.yaml
- Makefile
- env/prod
- env/stage
- go.mod
- go.sum
- messages/edge_applications/errors.go
- pkg/api/storage_api/storage_api.go
- pkg/cmd/edge_applications/build/build.go
- pkg/cmd/edge_applications/build/build_test.go
- pkg/cmd/edge_applications/edge_applications_test.go
- pkg/cmd/root/root.go
- pkg/constants/constants.go
**WHAT**
- Get version-id during build command;
- Add newly got version-id to azion.json file;
- Update functional tests;
- Update deploy and goreleaser routines.
> feat: get version-id during build command

- pkg/cmd/domains/list/list.go
- utils/helpers_test.go
**WHAT**
- Active as last field in listing, to follow the convention;
- Unit test for checkOrderField.
> chore: change listing and unit test

- messages/edge_applications/messages.go
- pkg/cmd/edge_applications/build/build.go
- pkg/cmd/edge_applications/publish/publish.go
**WHAT**
When build is called from publish:
- Check if Version-Id (MD5) of project is the same as the one saved in azion.json file;
- if they're the same, build step is skipped;
- if they are different, build is called normally and afterwards, a new version-id is generated and saved.
> chore: check project for mandatory build

- messages/device_groups/errors.go
- messages/device_groups/messages.go
- pkg/api/edge_applications/edge_applications.go
- pkg/cmd/device_groups/describe/describe.go
- pkg/cmd/device_groups/describe/describe_test.go
- pkg/cmd/device_groups/describe/fixtures/groups.json
- pkg/cmd/device_groups/device_groups.go
- pkg/cmd/device_groups/list/list.go
- pkg/cmd/edge_applications/build/build.go
- pkg/cmd/edge_applications/build/build_test.go
- pkg/cmd/edge_functions_instances/delete/delete.go
- pkg/cmd/origins/delete/delete.go
- pkg/cmd/origins/describe/describe.go
- pkg/cmd/rules_engine/delete/delete.go
- pkg/cmd/rules_engine/describe/describe.go
- pkg/cmd/rules_engine/list/list.go
- utils/errors.go
- utils/helpers.go
**WHAT**
- Add describe command to device groups;
- Unit tests;
- Command Runner with streamed logs (only when output-ctrl is disabled);
- Adjusted build command tests.
> feat: add describe command to device groups

- pkg/cmd/device_groups/list/list.go
- pkg/cmd/root/root.go
**WHAT**
- Fix duplicate commands originating from Conflict Resolution;
- Fix alignment.
> fix: remove duplicate commandas

- pkg/api/storage/storage.go
**WHAT**
Remove content type from storage-api client, as the API infers the type by itself.
> fix: remove content-type from storage-api client

- pkg/cmd/edge_applications/init/init.go
- pkg/cmd/edge_applications/init/init_test.go
- set name in json on command init static
> chore: set name in azin/azion.json on command init static

- pkg/upbin/update_binary.go
- pkg/upbin/update_binary_test.go
- removes the idea of using a prefix to avoid possible errors in the future and just takes all the numbers
> feat: prefix different than expected

- pkg/cmd/link/utils.go
**WHAT**
- If preset is nextjs, menu asking for preset and mode should not be shown.
> chore: should not show menu if preset is nextjs

- pkg/cmd/deploy/deploy.go
**WHAT**
- Remove dot-slash "./" from pathStatic. filepath.Walk function removes this when analyzing files, so when we call upload function we cannot trim the name because it will not contain the "./"
> chore: remove dot-slash from pathStatic

- pkg/api/domains/domains.go
- pkg/api/edge_applications/create.go
- pkg/api/edge_applications/edge_applications.go
- pkg/api/edge_functions/edge_functions.go
- pkg/api/rules_engine/rules_engine.go
- pkg/cmd/root/root.go
- pkg/cmd/update/edge_application/edge_application.go
- utils/helpers.go
**WHAT**
- Reset httpResp.body buffer, so it can be read again. There was an error, where the buffer would be read to create the debug message, however, later, when the function ErrorPerStatusCode would try to read it again, the buffer would be empty. This fixes that, reseting the buffer to its initial state;
- Add all debugs to the function as well;
> fix: reset httpResp buffer to be read again

- README.md
Seems like the command was based on the previous name of the binary and needed an update :smiley_cat:
> docs: update command for configuring token

- messages/create/domains/messages.go
- messages/create/edge_application/messages.go
- messages/create/rules_engine/messages.go
- messages/delete/domains/messages.go
- messages/describe/domains/messages.go
- messages/describe/edge_applications/messages.go
- messages/list/domains/messages.go
- messages/list/edge_applications/messages.go
- messages/update/domains/messages.go
- messages/update/edge_application/messages.go
- pkg/cmd/create/domains/domains.go
- pkg/cmd/create/edge_applications/edge_application.go
- pkg/cmd/delete/domains/domains.go
- pkg/cmd/delete/edge_application/edge_application.go
- pkg/cmd/delete/edge_application/edge_application_test.go
- pkg/cmd/delete/rules_engine/rules_engine.go
- pkg/cmd/describe/domains/domains.go
- pkg/cmd/describe/edge_applications/edge_applications.go
- pkg/cmd/describe/edge_applications/edge_applications_test.go
- pkg/cmd/describe/rules_engine/rules_engine.go
- pkg/cmd/list/domains/domains.go
- pkg/cmd/list/edge_applications/edge_applications.go
- pkg/cmd/update/domains/domains.go
- pkg/cmd/update/edge_application/edge_application.go
- pkg/cmd/update/edge_application/edge_application_test.go
**WHAT**
- Fix examples for `create edge-application`;
- Change `domains` to `domain`;
> chore: fix examples and command usages

- .goreleaser.yaml
**WHAT**
Change `doc` to `docs` when creating changelog in release page;
> refactor: change doc to docs in release builder

- messages/create/messages.go
- messages/delete/messages.go
- messages/describe/messages.go
- messages/list/messages.go
- messages/update/messages.go
- pkg/cmd/root/help.go
**WHAT**
- Add <subcommand> to help messages;
- Change `LOCAL OPTIONS` to `GLOBAL OPTIONS` in root command help;
- Before
```
$ azion -h
Azion CLI 1.2.0
[...]
LOCAL OPTIONS
-c, --config string      Sets the Azion configuration folder for the current command only, without changing persistent settings.
-d, --debug              Displays log at a debug level
-h, --help               Displays more information about the Azion CLI
-l, --log-level string   Displays log at a debug level (default "info")
-s, --silent             Silences log completely; mostly used for automation purposes
-t, --token string       Saves a given personal token locally to authorize CLI commands
-v, --version            version for azion
-y, --yes                Answers all yes/no interactions automatically with yes …
```
> chore: flags are shown as global to root command as well

- messages/vulcan/messages.go
- pkg/cmd/build/build.go
- pkg/cmd/build/run.go
- pkg/cmd/build/vulcan.go
- pkg/cmd/init/init.go
- pkg/cmd/init/utils.go
- pkg/cmd/link/utils.go
- pkg/token/models.go
- pkg/vulcan/vulcan.go
- pkg/vulcan/vulcan_test.go
- utils/helpers.go
**WHAT**
- Use latest version of vulcan as default, except:
- There is a new major version of Vulcan: in this case, we warn the user to update their CLI to use the new Vulcan version;
- First time using: we suggest a default version;
> chore: use latest vulcan version

- pkg/cmd/login/browser.go
**WHAT**
- Fix problem where param would be read twice, and save an empty token;
> fix: handler reading param twice #patch

- pkg/cmd/link/template.go
**WHAT**
- Preset and Mode were being saved incorrectly in azion.json file, thus causing errors when these fields were being verified by other commands;
> fix: saving preset and mode incorrectly

- messages/origin/messages.go
- pkg/cmd/create/origin/origin.go
- pkg/cmd/create/origin/origin_test.go
- pkg/cmd/update/origin/origin.go
- utils/helpers.go
**WHAT**
- Add missing fields to origin create and update:
- Creating object storage origin was impossible before this change.
> fix: add missing fields in origin create/update

- messages/root/messages.go
- pkg/cmd/init/init.go
- pkg/cmd/init/utils.go
- pkg/cmd/link/link.go
- pkg/cmd/link/utils.go
- pkg/cmd/root/post_command.go
- pkg/cmd/root/pre_command.go
- pkg/cmd/root/root.go
- pkg/token/models.go
- utils/helpers.go
**WHAT**
- ask user if they allow metrics to be collected (default: yes). 
- saving the answer in the settings.toml file, using the following pattern: (0 = not answered yet; 1 = authorized; 2 = not authorized);
- PersistentPostRunE added: 
- runs after every command is completed and updates the following metrics (if the user allowed):
- `total-commands-executed` (count of every command executed by the user);
- `command-subcommand` , for e.g.: `list-domain` (count of executions per command);
Metrics are being saved in a map of ints. In the future, when more complex metrics are added, we might need to update this variable to a map of interfaces perhaps;
> feat: add metrics collector to all commands

- go.mod
- pkg/cmd/deploy/manifest.go
**WHAT**
- If it's not the first run, skip updating rules engine/cache settings;
> fix: after the first deploy, we should not update rules engine

- go.mod
- messages/root/errors.go
- pkg/cmd/root/pre_command.go
- pkg/cmd/root/root.go
- pkg/config/config.go
- pkg/metric/count.go
- pkg/metric/segment.go
- pkg/token/models.go
- pkg/token/token.go
- pkg/token/token_test.go
Description:
The problem is related to the question of authorization to metrics that the idea is to be asked only once, only every time you set a new configuration this question needs to be answered for the new configuration we do not make the copy for the user to have the freedom to choose if in this new configuration. The real problem was that we confused the use of the flag that receives parameters even with the flag prefix and for this reason it is asked again.
fix: checks a value with a flag smell. chaves: 'parece de tamarindo é de limão, com sabor de groselha
fix: used the path of the directory and the expected behavior is the absolute path
> fix: update --config flag behavior and respect metrics acceptance input

- pkg/cmd/root/root.go
currently the azion command calls the azion init command and has been asked to switch back to the default behavior which is to call help
> refactor: command azion call helper no init

- CODEOWNERS
- pkg/cmd/create/personal_token/expiration_date.go
- pkg/cmd/create/personal_token/expiration_date_test.go
- pkg/cmd/list/personal_token/personal_token.go
- pkg/constants/constants.go
For some reason, the listing for personal tokens displayed a weird timestamp formatting for one of the items.
> fix: format no milliseconds

- messages/deploy/messages.go
- messages/link/errors.go
- pkg/api/edge_applications/edge_applications.go
- pkg/cmd/deploy/bucket.go
- pkg/cmd/deploy/deploy.go
- pkg/cmd/deploy/manifest.go
- pkg/cmd/deploy/requests.go
- pkg/cmd/edge_functions_instances/create/create.go
- pkg/cmd/init/template.go
- pkg/cmd/link/link.go
- pkg/cmd/link/template.go
- pkg/contracts/contracts.go
- utils/helpers.go
- Always retry when name is already taken for resources creation.
- `--auto` flag:
- This flag will make sure the flow is not interrupted and will run deploy command to its completion. It will automatically give a new name in case the original name used is repeated. 
- Update Instance args.json on deploy.
> chore: deploy command refactor

- pkg/cmd/link/link.go
Updated the regex to correctly capture the repository name even when there are dots in the user or repository name
> fix: name repo

- pkg/api/storage/storage.go
- pkg/cmd/build/build.go
- pkg/cmd/build/version_id.go
- pkg/cmd/deploy/bucket.go
- pkg/cmd/deploy/bucket_test.go
- utils/helpers.go
- Normalize the name given for the bucket
- Retry with another suffix until successful or for a maximum of 10x, using the pattern name_bucket_$timestamp
> feat: warroom

- messages/deploy/messages.go
- pkg/cmd/deploy/requests.go
- pkg/cmd/dev/dev.go
- utils/helpers.go
- Revert timestamp back to old format, as it was the same used in frontend;
- Remove build from dev command (Vulcan runs build prior to dev now);
- Add timestamp to domain name in case name is already in use;
> chore: add timestamp to domain name

- pkg/cmd/delete/edge_storage/bucket.go
- pkg/cmd/root/root.go
- pkg/schedule/bucket.go
- pkg/schedule/schedule.go
Before, it deleted the bucket but didn't remove it from the schedule file, causing errors
> fix: delete bucket

- messages/sync/errors.go
- messages/sync/messages.go
- pkg/cmd/root/root.go
- pkg/cmd/sync/sync.go
- pkg/cmd/sync/tasks.go
- pkg/contracts/contracts.go
**WHAT**
- Add sync command:
- This will check if there are rules engine created remotely that are not found in local azion.json file, and add them. 
TO DO [Future PRs]:
- Add sync to other resources;
- Add this flow to deploy command;
> feat: add sync command [rules engine only]

- pkg/cmd/login/login.go
- pkg/cmd/whoami/whoami.go
**WHAT**
- Use centralized output in `whoami` and `login` commands;
> chore: update outputs to centralized output

- pkg/cmd/deploy/purge.go
- pkg/cmd/dev/dev.go
**WHAT**
- fix: check if .edge/storage directory exists before reading it to purge files;
- fix: initialize structure with vulcan value in dev command;
> fix: check if .edge/storage exists before purging files

- messages/init/messages.go
- messages/sync/errors.go
- pkg/cmd/sync/tasks.go
**WHAT**
- Display message explaining that the user needs to deploy their project at least once before trying to sync;
> docs: improve sync error message when not deployed

- pkg/output/error.go
Playing around here I realized that the error output is strange when I misspell the version command and I get an error like this 
``` $ ~/Workspace  azion -version
$ ~/Workspace  azion -version
Error: unknown shorthand flag: 'e' in -ersion$ ~/Workspace
```
what it looks like
```
$ ~/Workspace  azion -version
Error: unknown shorthand flag: 'e' in -ersion$ 
$ ~/Workspace
```
> chore: better output error

- pkg/cmd/init/init.go
- pkg/vulcan/vulcan.go
- pkg/vulcan/vulcan_test.go
The `os.Rename` method in Go, as in many other systems, is most efficient when the file or directory is being moved within the same file system. When you try to move files between different file systems, such as from `/tmp`  to the working directory, the rename command cannot be used and results in an error.
On many Linux systems, the `/tmp` directory may be on a separate partition or device from the one where the destination directory is located. However, on macOS, this may not be a problem if the `/tmp` directory and the target directory are on the same file system.
> fix: invalid cross-device link

- messages/init/errors.go
- pkg/cmd/init/init.go
- pkg/cmd/init/init_test.go
- pkg/cmd/init/template_test.go
- pkg/cmd/init/utils.go
- pkg/cmd/init/utils_test.go
This file will be removed from future versions, so I'm just removing this dependency now.
> chore: read info.json instead of .vulcan

- pkg/cmd/deploy/deploy.go
- pkg/cmd/deploy_remote/deploy.go
- pkg/cmd/deploy_remote/requests.go
**WHAT**
- Forward auto flag to the deploy-remote command;
- This allows deploys from automated environments (such as script-runner) to use this feature;
> chore: forward auto flag to deploy remote

- .goreleaser.yaml
- messages/deploy/messages.go
- pkg/cmd/deploy/deploy.go
- pkg/cmd/deploy_remote/deploy.go
- pkg/manifest/manifest.go
- pkg/manifest/manifest_test.go
- If this flag IS NOT passed, resources no longer found in the manifest.json file will be deleted; 
- By passing the flag, you ignore this feature;
> feat: add prune flag

- messages/warmup/errors.go
- messages/warmup/messages.go
- pkg/cmd/root/root.go
- pkg/cmd/warmup/fixtures/html_sample.json
- pkg/cmd/warmup/fixtures/response.json
- pkg/cmd/warmup/requests.go
- pkg/cmd/warmup/warmup.go
- pkg/cmd/warmup/warmup_test.go
Implements a new CLI command to systematically crawl and preload URLs into the edge cache.
- **Recursive URL crawling** starting from a base URL
- **Concurrent processing** with configurable limits
- **Smart URL filtering** with blacklist for unwanted file types
- **Progress tracking** and detailed statistics
- **Error handling** with failed URL reporting
```bash
azion warmup --url "https://example.com"
azion warmup --url "https://example.com" --max-urls 500 --max-concurrent 5 --timeout 10000
```
- `--url`: Base URL to start cache warming (required)
- `--max-urls`: Maximum URLs to process (default: 1500)
- `--max-concurrent`: Concurrent requests limit (default: 2)
- `--timeout`: Request timeout in milliseconds (default: 8000)
- Follows existing CLI patterns and project structure
- …
> feat(warmup): add cache warming command with URL crawling

- scripts/v3_to_v4_converter.sh
```
patrick.menoti@FVFFQA7FQ6L4 scripts % ./v3_to_v4_converter.sh -h                                    
Usage: ./v3_to_v4_converter.sh [OPTIONS]
Convert azion.json from V3 to V4 format
Options:
-i, --input FILE    Input azion.json file (default: azion.json)
-o, --output FILE   Output file (default: azion.json.v4)
-v, --verbose       Enable verbose output
-b, --backup        Create a backup of the original file
-w, --create-workload  Create a workload if domain exists (requires Azion CLI)
-d, --dry-run       Show what would be done without making changes
-W, --workload-id ID  Use an existing workload ID instead of creating a new one
-h, --help          Display this help message
```
> feat: add script to transform v3 into v4 azion.json

- pkg/cmd/root/pre_command.go
- pkg/cmd/root/update_check_test.go
- pkg/github/github.go
- pkg/github/github_test.go
- pkg/metric/count.go
- The previous way was causing confusion due to showing an update message before homebrew updated with the new version. The new way will only show the update message after 24 hours of the new version being published.
> chore: show update message 24 hours after publishing
