pkg/api/edge_functions/edge_functions.go
pkg/cmd/edge_functions/describe/describe.go
pkg/cmd/edge_functions/describe/describe_test.go
pkg/cmd/edge_services/describe/describe.go
pkg/cmd/edge_services/resources/describe/describe.go
pkg/cmd/init/init.go
pkg/cmd/init/init_test.go
pkg/cmd/init/options.go
pkg/cmd/publish/publish.go
pkg/cmd/publish/publish_test.go
pkg/contracts/contracts.go
utils/helpers_test.go

* Removing javascript field requirements
* Domain name is the last message from "publish command" now
* Renamed flags "next" to "nextjs"

removing javascript field requirements-

---

CONTRIBUTING.md

Fixed the 'repo/issues' reference

doc: Fixed the 'repo/issues' reference

---

README.md

**WHAT**
Correct a small mistake in readme file.
**WHY** 
[NO ISSUE]

fix: typo in readme file

---

README.md
go.mod
go.sum
pkg/cmd/edge_functions/create/create.go
pkg/cmd/root/root.go

Related issues:
- [ENG-19924]
[ENG-19924]: https://aziontech.atlassian.net/browse/ENG-19924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Deploy - 2022/7/1

---

pkg/api/domains/domains.go
pkg/api/edge_applications/edge_applications.go
pkg/api/edge_functions/edge_functions.go
pkg/api/realtime_purge/realtime_purge.go

**WHAT**
The timeout error messages were missing from some of the API calls.
**WHY**
[ENG-20839]
[ENG-20839]: https://aziontech.atlassian.net/browse/ENG-20839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-20839] chore: add new error message to other APIs

---

pkg/api/domains/domains.go
pkg/api/edge_applications/edge_applications.go
pkg/api/edge_functions/edge_functions.go
pkg/api/realtime_purge/realtime_purge.go
pkg/cmd/edge_services/requests/request.go

**WHAT**
Increase timeout in CLI Calls, while we do not have a fix for SSO Slowdown. 
**WHY**
[ENG-21217]
[ENG-21217]: https://aziontech.atlassian.net/browse/ENG-21217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-21217] chore: change API Call timeout to 30 seconds

---

pkg/cmd/edge_functions/delete/delete.go
pkg/cmd/edge_functions/delete/delete_test.go
pkg/cmd/edge_functions/describe/describe.go
pkg/cmd/edge_functions/describe/describe_test.go
pkg/cmd/edge_functions/error_messages/errors.go
pkg/cmd/edge_functions/update/update.go
pkg/cmd/edge_functions/update/update_test.go
pkg/cmd/edge_services/delete/delete.go
pkg/cmd/edge_services/delete/delete_test.go
pkg/cmd/edge_services/describe/describe.go
pkg/cmd/edge_services/describe/describe_test.go
pkg/cmd/edge_services/error_messages/errors.go
pkg/cmd/edge_services/resources/create/create.go
pkg/cmd/edge_services/resources/create/create_test.go
pkg/cmd/edge_services/resources/delete/delete.go
pkg/cmd/edge_services/resources/delete/delete_test.go
pkg/cmd/edge_services/resources/describe/describe.go
pkg/cmd/edge_services/resources/describe/describe_test.go
pkg/cmd/edge_services/resources/list/list.go
pkg/cmd/edge_services/resources/list/list_test.go
pkg/cmd/edge_services/resources/update/update.go
pkg/cmd/edge_services/resources/update/update_test.go
pkg/cmd/edge_services/update/update.go
pkg/cmd/edge_services/update/update_test.go
utils/helpers.go
utils/helpers_test.go

**WHAT**
Change id `args` to `flags`.
**WHY**
[ENG-21999]
[ENG-21999]: https://aziontech.atlassian.net/browse/ENG-21999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-21999] chore: change args to flags in all commands

---

messages/configure/messages.go
messages/edge_functions/messages.go
pkg/cmd/configure/configure.go
pkg/cmd/edge_functions/create/create.go
pkg/cmd/edge_functions/delete/delete.go
pkg/cmd/edge_functions/describe/describe.go
pkg/cmd/edge_functions/edge_functions.go
pkg/cmd/edge_functions/list/list.go
pkg/cmd/edge_functions/update/update.go
pkg/cmd/edge_services/edge_services.go
pkg/cmd/root/help.go
pkg/cmd/version/version.go
pkg/cmd/webapp/webapp.go

**WHAT**
- Change help messages according to help messages document written by the tech writer and design teams.
- Change custom help message constructor.

[ENG-22164] chore: change help messages

---

messages/root/messages.go
pkg/cmd/edge_functions/edge_functions.go
pkg/cmd/edge_functions/list/list.go
pkg/cmd/edge_functions/update/update.go
pkg/cmd/root/root.go

[ENG-22164] fix: help messages

---

messages/configure/messages.go
messages/edge_functions/messages.go
messages/edge_services/messages.go
messages/version/messages.go
messages/webapp/messages.go
pkg/cmd/configure/configure.go
pkg/cmd/edge_services/create/create.go
pkg/cmd/edge_services/delete/delete.go
pkg/cmd/edge_services/describe/describe.go
pkg/cmd/edge_services/edge_services.go
pkg/cmd/edge_services/list/list.go
pkg/cmd/edge_services/resources/create/create.go
pkg/cmd/edge_services/resources/delete/delete.go
pkg/cmd/edge_services/resources/describe/describe.go
pkg/cmd/edge_services/resources/list/list.go
pkg/cmd/edge_services/resources/update/update.go
pkg/cmd/edge_services/update/update.go
pkg/cmd/version/version.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/publish/publish.go

**WHAT**
Update help messages for the following commands and their subcommands:
- `edge_services`
- `version`
- `webapp`

[ENG-22189] chore: update messages for edge_services, webapp and version

---

pkg/cmd/edge_services/create/create.go
pkg/cmd/edge_services/resources/resources.go
pkg/cmd/root/help.go
pkg/cmd/webapp/build/build.go
pkg/cmd/webapp/publish/publish.go
pkg/cmd/webapp/webapp.go

**WHAT**
Small fixes to problems found during validation.
Change cobraCmd to `<package>Cmd`.

fix help messages

---

.goreleaser.yaml
README.md

Related tasks:
- Add autocomplete to `azioncli`.

Deploy to Production - 2022/10/24

---

messages/webapp/errors.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go

- testing adjusted for new and refactored features of the init command
- removed init dependency for javascript, flareact and nextjs

chore: remove .sh dependency for nextjs, react and javascript from init command

---

go.mod
messages/webapp/errors.go
pkg/cmd/webapp/build/build.go

**WHAT**
- Update build command with steps previously found in webdev.sh file (azioncli-template);
- Webdev.sh for nextjs is not fully remvoed yet.

chore: remove .sh dependency for nextjs and flareact

---

messages/webapp/errors.go
pkg/cmd/webapp/publish/publish.go

**WHAT**
- Messages were not being properly formatted.

fix: formatting messages correctly

---

.github/workflows/deploy_prod.yml
.goreleaser.yaml
Makefile
env/local
env/prod
env/stage
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go

**WHAT**
- Stage binary now clones template's dev branch.  Previsously we had a problem where we had to push changes to the template to test changes in stage binary, but that would also affect production binary. Now we have separated them both into dev/main branches.

feat: stage binary now clones template's dev branch

---

env/prod
messages/webapp/errors.go
messages/webapp/messages.go
pkg/cmd/webapp/build/build.go
pkg/cmd/webapp/build/build_test.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go
pkg/cmd/webapp/publish/publish.go
pkg/cmd/webapp/publish/publish_test.go
pkg/contracts/contracts.go
utils/errors.go
utils/helpers.go

**WHAT**
- Add support to output control;
- `on-error` = only shows output when an error occurs;
- `disable` = shows the entire output;
- Update unit tests.

feat: add output control support

---

messages/webapp/messages.go
pkg/cmd/webapp/init/init.go

**WHAT**
- Remove redundant call to "getWorkingDir";
- Better output for init command.

chore: better output for init command

---

env/prod
pkg/cmd/webapp/build/build.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go
pkg/cmd/webapp/publish/publish.go
pkg/cmd/webapp/publish/publish_test.go
pkg/cmd/webapp/tests/webapp_test.go

**WHAT**
- Add functional testing for webapp commands (init, build, publish)
- Functions and http requests are being mocked

feat: add functional testing for webapp commands

---

Makefile
env/local
env/prod
env/stage
messages/webapp/errors.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go

- git clone by major
- testing git clone

feat: add git clone based on configured major version

---

pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go

- Incorrect logic for git clone of major has been resolved

fix: adjustment in logic was not correctly checking the version by major

---

Makefile
messages/webapp/errors.go
messages/webapp/messages.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go

- update message error for ErrorGetAllTags and ErrorInterateAllTags
- add custom message to flareact and javascript

feat: add custom initialization messages

---

pkg/cmd/webapp/init/init.go

- get the project name from azion.json

ref: get the project name from azion.json

---

messages/webapp/messages.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/init/init_test.go
pkg/cmd/webapp/init/options.go

- use autodect
- no expected flag --type

feat: implemented the use of autodetect 

---

messages/webapp/messages.go
pkg/cmd/webapp/init/init_test.go

**WHAT**
Adding new messages to azioncli

chore: add new cli messages

---

pkg/cmd/webapp/build/build.go

**WHAT**
- Remove unnecessary function call.

chore: minor refactor to build cmd

---

pkg/cmd/webapp/build/build.go
pkg/cmd/webapp/init/init.go
pkg/cmd/webapp/publish/package-lock.json
pkg/cmd/webapp/publish/publish.go
pkg/cmd/webapp/publish/publish_test.go
pkg/contracts/contracts.go

- customizable command for all points

Feat customizable commands

---

pkg/cmd/edge_applications/init/init.go

**WHAT**
- Main branch as default branch for template download.

chore: change default template branch

---

messages/edge_applications/errors.go
messages/edge_applications/messages.go
messages/edge_functions/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/describe/describe.go
pkg/cmd/edge_applications/describe/describe_test.go
pkg/cmd/edge_applications/edge_applications.go

**WHAT**
- Add describe command to edge_applications command tree;
- Unit tests.

feat: add describe command to edge_applications

---

messages/edge_applications/errors.go
messages/edge_applications/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/delete/delete.go
pkg/cmd/edge_applications/delete/delete_test.go
pkg/cmd/edge_applications/edge_applications.go

**WHAT**
- Add `Delete` command to Edge Applications command tree.
- Unit tests.

feat: add delete command to edge applications

---

pkg/cmd/edge_applications/list/list.go
pkg/cmd/edge_functions/list/list.go

- I was not respecting the size of the page

fix: when listing all items ignored page_size now fixed

---

pkg/cmd/domains/list/list.go

- add new column
-  adjust fields

fix: add new column in list details domains and adjust fields

---

messages/domains/errors.go
messages/domains/messages.go
pkg/api/domains/domains.go
pkg/cmd/domains/domains.go
pkg/cmd/domains/update/fixtures/update.json
pkg/cmd/domains/update/update.go
pkg/cmd/domains/update/update_test.go
pkg/cmd/edge_applications/delete/delete.go
pkg/cmd/edge_applications/publish/publish.go

**WHAT**
- Add update command to domains;
- Unit tests;
- `DigitalCertificateId` was left out for now, as we need to update the SDK.

feat: add update command to domains

---

go.mod
go.sum
messages/origins/errors.go
messages/origins/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/init/init.go
pkg/cmd/edge_applications/init/init_test.go
pkg/cmd/origins/list/fixtures/noorigins.json
pkg/cmd/origins/list/fixtures/origins.json
pkg/cmd/origins/list/list.go
pkg/cmd/origins/list/list_test.go
pkg/cmd/origins/origins.go
pkg/cmd/root/root.go

- new command origins
- sub command list is from origins
- test unit from list origins
- adjusted test unit sort tag

Feat: create command origins list

---

pkg/contracts/contracts.go

**WHAT**
- Add version-id to contracts; 
- Field was added to the template as well.

feat: add version id to contract

---

go.mod
go.sum
messages/origins/errors.go
messages/origins/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/init/init.go
pkg/cmd/origins/create/create.go
pkg/cmd/origins/create/create_test.go
pkg/cmd/origins/create/fixtures/create.json
pkg/cmd/origins/create/fixtures/response.json
pkg/cmd/origins/describe/describe.go
pkg/cmd/origins/describe/describe_test.go
pkg/cmd/origins/describe/fixtures/noorigins.json
pkg/cmd/origins/describe/fixtures/origins.json
pkg/cmd/origins/origins.go

- create command origins 
- test unit

Feat: create command create to origins

---

.github/workflows/deploy_stage.yml
pkg/api/storage_api/storage_api.go
pkg/cmd/edge_applications/build/build.go
pkg/cmd/edge_applications/edge_applications_test.go
pkg/cmd/edge_applications/init/init.go
pkg/cmd/edge_applications/init/init_test.go

**WHAT**
- Remove debugging commands;
- Add application_id verification.

fix: remove debugging commands

---

go.mod
go.sum
messages/edge_applications/messages.go
pkg/api/domains/domains.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/build/build_test.go

**WHAT**
- Update SDK version;
- Update Web Application messages to Edge Application.

chore: update SDK version

---

messages/edge_applications/errors.go
pkg/cmd/edge_applications/update/update.go
pkg/cmd/edge_applications/update/update_test.go

- case verified and implemented a validation
- test unit

fix: fixing the case when no field is passed to be updated

---

go.mod
go.sum
messages/cache_settings/errors.go
messages/cache_settings/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/cache_settings/cache_settings.go
pkg/cmd/cache_settings/create/create.go
pkg/cmd/cache_settings/create/create_test.go
pkg/cmd/cache_settings/create/fixtures/app_result.json
pkg/cmd/cache_settings/create/fixtures/app_result_no_acceleration.json
pkg/cmd/cache_settings/create/fixtures/create.json
pkg/cmd/cache_settings/create/fixtures/error
pkg/cmd/cache_settings/create/fixtures/result.json
pkg/cmd/edge_applications/describe/describe.go
pkg/cmd/origins/create/create.go
pkg/cmd/origins/create/create_test.go
pkg/cmd/origins/delete/delete.go
pkg/cmd/origins/delete/delete_test.go
pkg/cmd/origins/describe/describe.go
pkg/cmd/origins/describe/describe_test.go
pkg/cmd/origins/list/list.go
pkg/cmd/origins/list/list_test.go
pkg/cmd/origins/update/update_test.go
pkg/cmd/root/root.go
utils/helpers.go

**WHAT** 
- Add cache_settings create command;
- Unit tests;
- General refactors to other parts of the code.

feat: add cache settings create command

---

messages/cache_settings/errors.go
pkg/cmd/cache_settings/cache_settings.go

- merge conflict resolved
- adjustment of variables that disappeared in the merge

fix: merge conflict

---

messages/domains/errors.go
messages/domains/messages.go
messages/edge_applications/errors.go
messages/edge_applications/messages.go
messages/edge_functions/errors.go
messages/edge_functions/messages.go
messages/edge_services/errors.go
messages/edge_services/messages.go
pkg/cmd/edge_services/create/create_test.go
pkg/cmd/edge_services/resources/create/create_test.go

Starts the standardization process.

review-messages-errors

---

messages/cache_settings/errors.go
messages/cache_settings/messages.go
messages/domains/errors.go
messages/origins/errors.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/cache_settings/cache_settings.go
pkg/cmd/cache_settings/describe/describe.go
pkg/cmd/cache_settings/describe/describe_test.go
pkg/cmd/cache_settings/describe/fixtures/cache_settings.json
pkg/cmd/origins/describe/describe.go

- create command describe
- test unit

Feat: cache settings describe

---

messages/domains/errors.go
pkg/cmd/domains/list/list.go
utils/helpers.go

**WHAT**
- Add new fields to `domain list --details`;
- Check new error when sending `order_by` query param.

chore: add new fields to domain list

---

messages/edge_applications/messages.go
pkg/cmd/edge_applications/init/init.go

- bug adjusted, CDN does not depend on package.json anymore

fix: fixed bug cdn dependency on package.json

---

pkg/cmd/edge_applications/init/init.go

**WHAT**
- Remove the update of package.json build script;

chore: remove update to build script

---

pkg/cmd/edge_applications/build/build.go
pkg/cmd/edge_applications/build/build_test.go

**WHAT**
- Since we will be using Storage-API to upload the static files, we no longer need to use AWS;

chore: remove user input of AWS credentials

---

pkg/cmd/edge_applications/.fixtures/domain.json
pkg/cmd/edge_applications/.fixtures/edge_application.json
pkg/cmd/edge_applications/.fixtures/edge_function.json
pkg/cmd/edge_applications/.fixtures/pack.json
pkg/cmd/edge_applications/.fixtures/rule.json
pkg/cmd/edge_applications/.fixtures/rules.json
pkg/cmd/edge_applications/edge_applications_test.go
pkg/cmd/edge_applications/publish/publish.go

- Test integration
- start refactoring

ref: add storage api integration test and test refactoring start

---

messages/rules_engine/errors.go
messages/rules_engine/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/api/storage/storage.go
pkg/cmd/root/root.go
pkg/cmd/rules_engine/list/fixtures/norules.json
pkg/cmd/rules_engine/list/fixtures/rules.json
pkg/cmd/rules_engine/list/list.go
pkg/cmd/rules_engine/list/list_test.go
pkg/cmd/rules_engine/rules_engine.go

**WHAT**
- Add list command to rules engine;
- Unit tests.

feat: add list command to rules engine

---

pkg/cmd/edge_applications/build/build.go

**WHAT**
- Change version-id generation;
- there was a bug in the go library we used;

chore: change versionID generation

---

go.sum
messages/rules_engine/errors.go
messages/rules_engine/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/rules_engine/delete/delete.go
pkg/cmd/rules_engine/delete/delete_test.go
pkg/cmd/rules_engine/rules_engine.go

- create new command delete from rules engine
- create 2 cases test unit

feat: new command delete from rules engine

---

messages/edge_functions_instances/errors.go
messages/edge_functions_instances/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_functions_instances/delete/delete.go
pkg/cmd/edge_functions_instances/delete/delete_test.go
pkg/cmd/edge_functions_instances/edge_functions_instances.go
pkg/cmd/root/root.go

**WHAT**
- Add delete command to edge functions instances;
- Unit tests.

feat: add delete command for edge functions instances

---

messages/edge_functions_instances/errors.go
messages/edge_functions_instances/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_functions_instances/describe/describe.go
pkg/cmd/edge_functions_instances/describe/describe_test.go
pkg/cmd/edge_functions_instances/describe/fixtures/instance.json
pkg/cmd/edge_functions_instances/edge_functions_instances.go
pkg/cmd/rules_engine/describe/describe_test.go

**WHAT**
- add describe command to edge functions instances
-  unit tests
- fix typo

feat: add describe command to edge functions instances

---

messages/edge_functions_instances/errors.go
messages/edge_functions_instances/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/cmd/edge_applications/publish/publish.go
pkg/cmd/edge_functions_instances/create/.fixtures/create.json
pkg/cmd/edge_functions_instances/create/.fixtures/resp.json
pkg/cmd/edge_functions_instances/create/create.go
pkg/cmd/edge_functions_instances/create/create_test.go
pkg/cmd/edge_functions_instances/edge_functions_instances.go
pkg/cmd/edge_functions_instances/list/list.go

- created command create
- test unit

feat: created command create functions instances

---

pkg/cmd/edge_functions_instances/edge_functions_instances.go

**WHAT**
- Remove repeated command;

fix: remove repeated command from instances

---

pkg/cmd/device_groups/create/create.go

fix: change command create incorrect

---

messages/device_groups/messages.go

fix: duplicate word in device groups update success message

---

messages/edge_applications/messages.go
pkg/cmd/edge_applications/publish/publish.go

**WHAT**
- Add hint for domain update after user publishes its project.

feat: add hint for domain update after publish

---

pkg/cmd/edge_applications/init/init.go
pkg/cmd/edge_applications/publish/publish.go

fix: add version id on post

---

messages/device_groups/messages.go

fix: resolv conflict

---

pkg/cmd/edge_applications/publish/publish.go

- reading azion.json after build

fix: version id error 

---

pkg/api/storage/storage.go
pkg/cmd/edge_applications/publish/publish.go
utils/helpers.go

- get the content type based on file type

feat: get the content type based on file type

---

go.mod
go.sum
pkg/cmd/edge_applications/publish/publish.go
utils/helpers.go

feat: added the package mimemagic to identfy the mimetypes thats files

---

messages/edge_applications/messages.go
pkg/cmd/edge_applications/edge_applications_test.go
pkg/cmd/edge_applications/publish/publish.go

**WHAT**
- Add default origin;
- Add `--path` flag and default value of `public`;
- Update tests;

chore: add default origin

---

pkg/cmd/edge_applications/init/init.go
pkg/cmd/edge_applications/init/init_test.go
pkg/cmd/edge_applications/publish/publish.go

- write version id in function.js

fix: write version id in function.js

---

pkg/cmd/edge_applications/publish/publish.go

**WHAT**
- Remove debugging println.

fix: remove testing println

---

messages/variables/errors.go
messages/variables/messages.go
pkg/api/edge_functions/edge_functions.go
pkg/api/variables/variables.go
pkg/cmd/variables/update/fixtures/variable.json
pkg/cmd/variables/update/update.go
pkg/cmd/variables/update/update_test.go
pkg/cmd/variables/variables.go

**WHAT**
- Add update command to variables command tree;
- Unit tests;
- Other small fixes;

feat: add update command to variables command tree

---

messages/variables/errors.go
messages/variables/messages.go
pkg/api/variables/variables.go
pkg/cmd/variables/create/.fixtures/create.json
pkg/cmd/variables/create/.fixtures/response.json
pkg/cmd/variables/create/create.go
pkg/cmd/variables/create/create_test.go
pkg/cmd/variables/variables.go

- add sub command create for variables command tree;
- unit tests;

feat: created command create with subcommand from variable

---

pkg/cmd/variables/delete/delete.go
pkg/cmd/variables/list/list.go

**WHAT**
- Small fix in list command;

fix: call correct method in list

---

messages/variables/messages.go
pkg/cmd/variables/create/create.go
pkg/cmd/variables/delete/delete.go
pkg/cmd/variables/describe/describe.go
pkg/cmd/variables/update/update.go

**WHAT**
- Fix example not aligned;
- Edit some help messages.

fix: edit examples and messages

---

go.mod
go.sum
pkg/api/edge_applications/edge_applications.go
pkg/api/storage/storage.go
pkg/cmd/edge_applications/build/build.go
pkg/cmd/variables/describe/describe.go

**WHAT**
- Update SDK version;
- Update examples;
- Minor code refactor;

chore: update SDK version and make necessary changes

---

go.mod
go.sum

**WHAT**
- Edge Applications List was retuning memory addresses instead of values;

fix: update SDK version

---

go.mod
go.sum
messages/variables/errors.go
pkg/api/variables/variables.go
pkg/cmd/variables/create/create.go
pkg/cmd/variables/create/create_test.go
pkg/cmd/variables/delete/delete_test.go
pkg/cmd/variables/describe/describe_test.go
pkg/cmd/variables/list/list_test.go
pkg/cmd/variables/update/update_test.go

**WHAT**
- `secret` field is not mandatory in create command;

fix: alter secret to be optional

---

pkg/cmd/edge_applications/init/init.go
pkg/cmd/edge_applications/publish/publish.go
pkg/logger/logger.go

- replaced FPrintf with FInfo which is managed by loglevel

fix: replaced FPrintf with FInfo which is managed by loglevel

---

go.mod
go.sum
pkg/cmd/domains/list/list.go
pkg/cmd/variables/list/list.go
utils/helpers.go

- formatted value field, if the size is too large
- refactor list variables

fix: formatted value field, if the size is too large

---

go.mod
go.sum
pkg/api/edge_applications/edge_applications.go
pkg/cmd/domains/list/list.go
pkg/cmd/rules_engine/create/.fixtures/create.json
pkg/cmd/rules_engine/create/.fixtures/create_conditional_empty.json
pkg/cmd/rules_engine/create/.fixtures/create_name_empty.json
pkg/cmd/rules_engine/create/.fixtures/resp_phase_request.json
pkg/cmd/rules_engine/create/.fixtures/resp_phase_response.json
pkg/cmd/rules_engine/create/create.go
pkg/cmd/rules_engine/describe/describe.go

**WHAT**
- Add description field to rules engine;
- Add fields to fixtures;
- Update function name;

chore: add description field to rules engine

---

Makefile
pkg/upbin/packages_managers.go

- logic adjustment stopping execution when upgrading to brew case

fix: azion cli binary upgrade tuning

---

.goreleaser.yaml

- https://goreleaser.com/deprecations/?h=archives.replacements#archivesreplacements

fix: deprecated overrides tweak

---

scripts/completions.sh

chore: added flag not update in generated auto completion

---

.goreleaser.yaml
scripts/completions.sh

**WHAT**
- Fix completions.sh script;

Deploy to Production - 2023/07/21

---

.gitignore
Makefile
cmd/azion/main.go
cmd/azioncli/main.go
cmd/gen_docs/main_test.go
messages/root/messages.go
pkg/cmd/version/version.go
pkg/upbin/replace_bin.go

**WHAT**
- Rename bin to `azion`;

chore: change bin name from azioncli to azion

---

pkg/cmd/root/root.go
pkg/cmd/version/version.go

**WHAT**
- `--version` \ `-v` option now shows Version 1.0.0 in bold;
- Set description in root command to bold;

feat: update --version option

---

pkg/cmd/root/help.go
pkg/cmd/root/root.go

feat: added colors in help

---

pkg/upbin/packages_managers.go

- Error when using exec.Command to run "brew upgrade azioncli "

fix: exec command upgrade azioncli

---

.github/workflows/deploy_prod.yml
.github/workflows/deploy_stage.yml
.goreleaser.yaml

chore: rename to azion

---

pkg/config/config.go

- config command must not have root path

fix: config command must not have root path

---

messages/init/messages.go
pkg/cmd/edge_applications/init/init.go
pkg/cmd/init/init.go
pkg/cmd/init/template.go
pkg/cmd/root/root.go
pkg/contracts/contracts.go

**WHAT**
- Fixed bug where Mode was not written to azion.json;
- Fixed bug where even after selecting template, the user was presented an error saying they needed to send flags;

fix: minor bugs fixed

---

pkg/cmd/init/init.go
pkg/cmd/root/help.go

chore: azioncli to azion

---

messages/build/errors.go
messages/build/messages.go
messages/dev/errors.go
messages/dev/messages.go
pkg/cmd/build/vulcan.go
pkg/cmd/deploy/deploy.go
pkg/cmd/dev/dev.go
pkg/cmd/dev/vulcan.go
pkg/cmd/edge_applications/ls/ls.go
pkg/cmd/init/init.go
pkg/cmd/init/utils.go
pkg/cmd/root/root.go

**WHAT**
- Add `dev` command;
- This calls `vulcan run` and starts a local development/test server;

feat: add dev command

---

pkg/cmd/deploy/worker.go
pkg/cmd/link/utils.go
pkg/cmd/personal-token/list/list.go
pkg/cmd/personal-token/personal-token.go

**WHAT**
- Change some debug messages;
- Fix problem where --yes flag would not apply to link command question;
- Add a space in list: `EXPIRESAT` -> `EXPIRES AT`
- Add delete command to personal token command structure;

chore: serious of minor fixes

---

pkg/cmd/build/vulcan.go
pkg/cmd/deploy/deploy.go
pkg/cmd/dev/vulcan.go
pkg/cmd/edge_applications/ls/ls.go
pkg/cmd/init/utils.go
pkg/cmd/link/utils.go

- hanged the static destination directory to storage and changed the vulcan pinned version to 1.3

fix: changes vulcan 

---

pkg/cmd/build/vulcan.go
pkg/cmd/dev/vulcan.go
pkg/cmd/edge_applications/ls/ls.go
pkg/cmd/init/utils.go
pkg/cmd/link/utils.go

- chage version vulcan to 1.4 and change run to dev

chore: chage version vulcan to 1.4 and change run to dev

---

messages/personal-token/errors.go
pkg/cmd/personal-token/create/create.go
utils/helpers.go

- valid struct and change message

fix: valid struct and change message

---

pkg/cmd/deploy/worker.go

**WHAT**
- Skip upload of empty file;

Empty file

---

go.mod
go.sum
messages/init/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/api/storage/storage.go
pkg/cmd/build/vulcan.go
pkg/cmd/deploy/requests.go
pkg/cmd/dev/vulcan.go
pkg/cmd/init/init.go
pkg/cmd/init/utils.go
pkg/cmd/link/link.go
pkg/cmd/link/utils.go
utils/helpers.go

**WHAT**
- Update vulcan to 1.7.0;
- Update Rules Engine to be compatible with next - compute;
- Show vulcan installation logs;

chore: update vulcan to 1.7.0

---

pkg/cmd/root/root.go

chore: comment command create

---

.goreleaser.yaml

**WHAT**
- Add chore to release page as well, with the subtitle "Improvements".

chore: improve releases page

---

pkg/api/domains/domains.go
pkg/api/edge_applications/edge_applications.go
pkg/api/edge_functions/edge_functions.go
pkg/cmd/init/utils.go

**WHAT**
- Better debug messages;
- Fix problem where Vite would break init command;

chore: add better debug messages

---

messages/edge_applications/errors.go
pkg/cmd/update/edge_application/edge_application.go
pkg/cmd/update/edge_application/fixtures/response.json
pkg/cmd/update/edge_application/fixtures/update.json
utils/helpers.go

**WHAT**
- Add an additional debug message;
- Remove debug println;
- Remove read-only field as an option in update/edge-application command;
- Personalized message when name is already in use;

fix: various minor fixes [check description]

---

messages/create/rules_engine/errors.go
messages/update/rules_engine/errors.go
pkg/api/rules_engine/rules_engine.go
pkg/cmd/create/rules_engine/rules_engine.go
pkg/cmd/update/rules_engine/rules_engine.go

**WHAT**
- Fix bug where target{} sent through json file (--in flag) would not be recognized and would break unmarshal;

fix: target{}, when sent via --in flag, would not be recognized

---

.goreleaser.yaml

**WHAT**
- Update deprecated fields: `tap` -> `repository`;
- Add (now) mandatory field: `maintainer`;
- Add test field:

chore: improve .goreleaser file

---

pkg/cmd/list/personal_token/personal_token.go

- checks if the field is null before trying to access it

refactor: checks is null

---

messages/create/edge_application/messages.go
pkg/cmd/create/edge_applications/edge_application.go

- flag removed field unknown to api

fix: flag removed field unknown to api

---

.goreleaser.yaml

**WHAT**
- Remove duplicate key entry;

fix: remove duplicate goreleaser entry

---

.goreleaser.yaml

**WHAT**
- Separate goreleaser test arguments;

refactor: separate goreleaser test

---

.goreleaser.yaml
pkg/api/rules_engine/rules_engine.go
pkg/cmd/create/domains/domains.go
pkg/cmd/create/rules_engine/rules_engine.go
pkg/cmd/update/domains/domains.go
pkg/cmd/update/edge_application/edge_application.go
pkg/cmd/update/rules_engine/rules_engine.go

**WHAT**
- Apply utils for reading sent file;
- Update goreleaser test case;

chore: apply utils to reduce code size #patch

---

utils/errors.go
utils/helpers.go

**WHAT**
- add message when context is cancelled during interactive input;

chore: add message when context is cancelled

---

pkg/cmd/build/vulcan.go
pkg/cmd/dev/vulcan.go
pkg/cmd/init/utils.go
pkg/cmd/link/utils.go
pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

-  centralizing the vulcan installation command

refactor: centralizing the vulcan installation command

---

.github/workflows/deploy_prod.yml
.goreleaser.yaml
messages/list/origin/errors.go
messages/list/origin/messages.go
pkg/api/edge_applications/edge_applications.go
pkg/api/origin/origin.go
pkg/cmd/deploy/deploy.go
pkg/cmd/deploy/requests.go
pkg/cmd/list/list.go
pkg/cmd/list/origin/fixtures/noorigins.json
pkg/cmd/list/origin/fixtures/origins.json
pkg/cmd/list/origin/origin.go
pkg/cmd/list/origin/origin_test.go
pkg/cmd/origins/create/create.go
pkg/cmd/origins/delete/delete.go
pkg/cmd/origins/describe/describe.go
pkg/cmd/origins/list/list.go
pkg/cmd/origins/update/update.go

**WHAT**
- Add list origin command;
- Unit tests;
- Fix: list edge-application ACTIVE field in the correct place;

feat: add list/origin command #minor

---

messages/delete/edge_application/messages.go
messages/delete/origin/errors.go
messages/delete/origin/messages.go
pkg/api/domains/domains.go
pkg/api/origin/origin.go
pkg/cmd/delete/delete.go
pkg/cmd/delete/edge_application/edge_application.go
pkg/cmd/delete/origin/origin.go
pkg/cmd/delete/origin/origin_test.go
pkg/cmd/list/origin/origin.go
pkg/cmd/list/origin/origin_test.go

**WHAT**
- Add delete origin command;
- Unit tests;
- Refactor SDK calls to check for nil httpResp;

feat: add delete/origin command

---

messages/cache_setting/messages.go
pkg/cmd/delete/cache_setting/cache_setting.go
pkg/cmd/describe/cache_setting/cache_setting.go
pkg/cmd/describe/cache_setting/cache_setting_test.go
pkg/cmd/describe/cache_setting/fixtures/cache_settings.json
pkg/cmd/describe/describe.go

**WHAT**
- describe cache-setting command;
- unit tests;
- small refactor;

feat: add describe/cache-setting command

---

messages/edge_function/messages.go
pkg/cmd/describe/describe.go
pkg/cmd/describe/edge_function/edge_function.go
pkg/cmd/describe/edge_function/edge_function_test.go
pkg/cmd/edge_functions/edge_functions.go

**WHAT**
- `describe edge-function` command;
- unit tests;

feat: add describe/edge-function command

---

messages/edge_function/messages.go
pkg/api/edge_function/edge_function.go
pkg/cmd/create/edge_function/edge_function.go
pkg/cmd/create/edge_function/edge_function_test.go
pkg/cmd/update/edge_function/edge_function.go
pkg/cmd/update/edge_function/edge_function_test.go

**WHAT**
- Update usage;
- Change flag `--in` to `--file`;
- Check for unsent flags ONLY if `--file` was not sent;
- Update tests;
- Remove unused messages;

refactor: small corrections to edge-function subcommands

---

messages/root/messages.go
pkg/cmd/root/root.go

**WHAT**
- Improve help message for log-level flag;

chore: improve help message for log-level flag #patch

---

pkg/cmd/update/edge_application/edge_application.go

**WHAT**
- Improve examples;
- Fix boolean fields;

refactor: improve examples

---

messages/edge_function/messages.go
pkg/cmd/create/edge_function/edge_function.go

**WHAT**
- Update input message for active field (edge-function);

refactor: update input message

---

go.sum
messages/logout/messages.go

**WHAT**
- Update logout message;

refactor: update logout message

---

pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

**WHAT**
- Update `Vulcan` to version 2.1.0;
- Update tests;

chore: update vulcan to 2.1.0 #patch

---

go.mod
go.sum
messages/login/errors.go
messages/login/messages.go
pkg/cmd/login/browser.go
pkg/cmd/login/login.go
pkg/cmd/login/terminal.go
pkg/cmd/logout/logout.go
pkg/logger/logger.go
pkg/token/token.go

**WHAT**
- Browser login;
- Logout now only deletes personal token if UUID is found;

feat: browser login

---

.github/workflows/deploy_prod.yml
.github/workflows/deploy_stage.yml
.github/workflows/generate_docs.yml
.github/workflows/test_and_build.yml
Dockerfile
go.mod

**WHAT**
- Update go version to 1.21;

chore: update go version to 1.21 #patch

---

pkg/cmd/root/pre_command.go

**WHAT**
- Change value to 0 to avoid atoi errors;

fix: change string to 0

---

pkg/cmd/root/pre_command.go

**WHAT**
- Check ONLY if latest is bigger than current: we were checking if it was bigger than or equal to;

fix: only test if latest is bigger than current #patch

---

.github/workflows/test_vulcan.yml
messages/cache_setting/messages.go
messages/create/domain/messages.go
messages/create/personal_token/messages.go
messages/create/rules_engine/messages.go
messages/delete/domain/messages.go
messages/delete/edge_application/messages.go
messages/delete/personal_token/messages.go
messages/delete/rules_engine/messages.go
messages/describe/domain/messages.go
messages/describe/edge_applications/messages.go
messages/describe/rules_engine/messages.go
messages/edge_function/messages.go
messages/list/cache_settings/messages.go
messages/list/rules_engine/messages.go
messages/login/messages.go
messages/origin/messages.go
messages/root/messages.go
messages/update/domain/messages.go
messages/update/edge_application/messages.go
messages/update/rules_engine/messages.go
pkg/cmd/create/edge_applications/edge_application.go
pkg/cmd/login/browser.go
pkg/cmd/root/pre_command.go
pkg/token/token.go
scripts/test.sh

- Better version notification;
- Improved input messages;

Deploy to Production - 2023/12/11

---

pkg/api/storage/storage.go
pkg/cmd/deploy/manifest.go
pkg/cmd/deploy/requests.go
utils/helpers.go

**WHAT**
- Rewrite deliver routes to get index.html correctly;

chore: rewrite static routes

---

messages/logs/http/errors.go
messages/logs/http/messages.go
pkg/api/graphql/cells/cells.go
pkg/api/graphql/http/http.go
pkg/cmd/logs/http/http.go
pkg/cmd/logs/logs.go

**WHAT**
- Add http events logs command;
- Change query to a `const`;

feat: add http events logs

---

pkg/cmd/create/origin/origin.go
utils/helpers.go

**WHAT**
- Let user input empty prefix;

fix: input did not allow empty fields

---

pkg/cmd/link/utils.go

- item empty removed in presets

fix: item empty removed in presets

---

messages/delete/edge_application/messages.go
messages/unlink/messages.go
pkg/cmd/delete/edge_application/cascade.go
pkg/cmd/delete/edge_application/edge_application.go
pkg/cmd/delete/edge_application/edge_application_test.go
pkg/cmd/root/root.go
pkg/cmd/unlink/unlink.go
pkg/cmd/unlink/utils.go

**WHAT**
- Unlink command:
- deletes local files used by CLI to track project;
- may delete remote resources as well, if authorized by user;

feat: add unlink command

---

pkg/cmd/deploy/manifest.go
pkg/vulcan/vulcan.go

- removed check routes next and added cookie forward to function next

refactor: routes next

---

pkg/cmd/init/utils.go
pkg/cmd/link/utils.go
pkg/cmd/root/post_command.go
pkg/cmd/root/pre_command.go
pkg/cmd/unlink/utils.go
utils/helpers.go

- enable flag global ours inputs 'y/N'

fix: enable flag global

---

Makefile
env/prod
pkg/cmd/root/pre_command.go
pkg/metric/metric.go

-  check  command completion ignored metrics

fix: check  command completion ignored metrics 

---

pkg/api/edge_applications/cache_setting.go
pkg/cmd/deploy/manifest.go

- create cache policy and define cache for function

fix: create cache policy and define cache for function

---

messages/deploy/messages.go
pkg/cmd/deploy/bucket.go
pkg/cmd/deploy/requests.go

**WHAT**
- save domain id and bucket name as soon as they are successfully created;
- check correct error when bucket name is already in use;

fix: deploy was not writing domain id to azion.json #patch

---

messages/whoami/errors.go
messages/whoami/messages.go
pkg/cmd/root/root.go
pkg/cmd/whoami/whoami.go

**WHAT**
- Add whoami command:
- prints email of the user currently logged in;
- returns an error if email field is empty;

feat: add whoami command

---

messages/build/errors.go
messages/build/messages.go
pkg/cmd/build/build.go
pkg/cmd/build/run.go
pkg/cmd/build/vulcan.go
pkg/cmd/deploy/deploy.go
pkg/cmd/dev/dev.go
pkg/contracts/contracts.go

**WHAT**
Add:
- `--entry`, `--useOwnWorker`, `--useNodePolyfill` flags to build command;

chore: add missing vulcan build flags

---

pkg/cmd/build/build.go
pkg/cmd/build/run.go
pkg/cmd/init/template.go
pkg/cmd/link/template.go
pkg/contracts/contracts.go

**WHAT**
- Saving the project root was causing problems when/if user changed the location of their project;

fix: remove projectRoot var to avoid build problems

---

CODEOWNERS
pkg/cmd/deploy/manifest.go

**WHAT**
- Ignore cache settings creation for Javascript and Typescript types;

fix: ignore cache-settings for js and ts types

---

pkg/cmd/deploy/deploy.go
pkg/cmd/deploy/deploy_test.go
pkg/cmd/deploy/fixtures/create_app.json
pkg/cmd/deploy/manifest.go
pkg/cmd/deploy/requests.go

- Always update function with new prefix;
- Skip cache_settings creation if already created;

fix: deploy would not update bucket and function

---

pkg/api/realtime_purge/realtime_purge.go
pkg/cmd/deploy/requests.go
pkg/cmd/root/help.go
pkg/cmd/root/root.go

**WHAT**
- Change purge URL to Wildcard Purge;

chore: change purge url to purge wildcard

---

pkg/cmd/deploy/requests.go

**WHAT**
- Display regular domains instead the one with wildcard applied;

refactor: do not show wildcard domain name

---

messages/root/errors.go
pkg/cmd/root/root.go

**WHAT**
- If RunE is not found, PersistentPreRunE will not be run;

chore: add RunE back to root command

---

messages/build/messages.go
messages/dev/messages.go
pkg/cmd/build/build.go
pkg/cmd/build/run.go
pkg/cmd/dev/dev.go
pkg/cmd/dev/vulcan.go
pkg/contracts/contracts.go

Changes:
- Add --firewall flag for build and dev commands to be used for edge firewall functions

feat: add firewall flag for local dev and build

---

messages/link/messages.go
pkg/cmd/link/link.go
pkg/github/github.go
pkg/vulcan/vulcan.go
utils/errors.go

added the remote argument, responsible for the remote repository clone of the link command

feat: command link flag --remote

---

go.mod
go.sum
messages/purge/errors.go
messages/purge/messages.go
pkg/api/realtime_purge/realtime_purge.go
pkg/cmd/deploy/requests.go
pkg/cmd/purge/purge.go
pkg/cmd/purge/purge_test.go
pkg/cmd/purge/requests.go
pkg/cmd/root/root.go

- Add purge command;
- urls, wildcard, cache-keys as flags, determining which type of purge will be carried out (more than one is available at once)

feat: add purge command

---

messages/deploy/messages.go
pkg/cmd/deploy/deploy.go
pkg/cmd/deploy/upload.go

- Check if storage folder exists: 
- If so, upload statics;
- Otherwise, show a debug message saying we will skip upload;

chore: check for storage directory

---

messages/cache_setting/messages.go
messages/delete/edge_application/messages.go
messages/delete/personal_token/messages.go
messages/delete/rules_engine/messages.go
messages/edge_function/messages.go
messages/edge_functions_instances/messages.go
messages/origin/messages.go
messages/variables/messages.go
pkg/cmd/delete/cache_setting/cache_setting.go
pkg/cmd/delete/edge_application/cascade.go
pkg/cmd/delete/edge_application/edge_application.go
pkg/cmd/delete/edge_application/edge_application_test.go
pkg/cmd/delete/edge_function/edge_function.go
pkg/cmd/delete/edge_function/edge_function_test.go
pkg/cmd/delete/edge_storage/bucket.go
pkg/cmd/delete/edge_storage/object.go
pkg/cmd/delete/edge_storage/object_test.go
pkg/cmd/delete/origin/origin.go
pkg/cmd/delete/origin/origin_test.go
pkg/cmd/delete/personal_token/personal_token.go
pkg/cmd/delete/rules_engine/rules_engine.go
pkg/cmd/delete/variables/variables.go
pkg/cmd/delete/variables/variables_test.go

**WHAT**
- Use new centralized output for delete commands;

refactor: update delete output

---

pkg/cmd/describe/origin/origin_test.go
pkg/manifest/manifest.go
pkg/manifest/request.go

- Remove unused commented code;
- One loop instead of two, for origin conf;

chore: remove unused code

---

messages/manifest/errors.go
pkg/manifest/fixtures/cachesuccess.json
pkg/manifest/fixtures/manifest.json
pkg/manifest/fixtures/rulessuccess.json
pkg/manifest/manifest.go
pkg/manifest/manifest_test.go
pkg/manifest/request.go

**WHAT**
- Add unit tests to manifest.json;

tests: add unit tests to manifest functions

---

pkg/cmd/build/vulcan.go
pkg/cmd/dev/dev.go
pkg/cmd/dev/vulcan.go
pkg/cmd/init/utils.go
pkg/cmd/link/utils.go
pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

**WHAT**
- If `--debug` flag if passed to CLI, we forward it to Vulcan;

chore: vulcan on debug mode

---

pkg/cmd/delete/cache_setting/cache_setting.go
pkg/cmd/delete/cache_setting/cache_setting_test.go

**WHAT**
- Update cache-setting-id flag;
- Update example;

refactor: update cache-setting-id flag

---

messages/deploy/messages.go
pkg/cmd/deploy/bucket.go
pkg/cmd/deploy/requests.go

**WHAT**
- Add timestamp to the end of edge application name, in case the used name is taken;
- Add more info messages to deploy flow;

chore: add info messages during deploy

---

messages/init/messages.go
messages/link/messages.go

**WHAT**
- Remove extra new line;

refactor: remove extra new line

---

pkg/output/describe.go

**WHAT**
- Check for nil value to avoid invalid memory address;

chore: check for nil value

---

go.mod
go.sum
messages/init/errors.go
messages/init/messages.go
messages/link/errors.go
messages/link/messages.go
pkg/cmd/init/init.go
pkg/cmd/link/link.go
pkg/github/github.go
utils/helpers.go

**WHAT**
- Ask user if they want to add files generated by Vulcan to their .gitignore file;

feat: add files to gitignore

---

messages/logout/messages.go
messages/reset/errors.go
messages/reset/messages.go
pkg/cmd/logout/logout.go
pkg/cmd/reset/reset.go
pkg/cmd/root/root.go
pkg/logger/logger.go

**WHAT**
- Add reset command:
- This resets settings.toml to default;
- Logs out before, if possible;

feat: add reset command

---

messages/deploy/messages.go
pkg/api/rules_engine/rules_engine.go
pkg/cmd/deploy/deploy.go
pkg/cmd/sync/sync.go
pkg/cmd/sync/tasks.go
pkg/contracts/contracts.go
pkg/manifest/fixtures/manifest.json
pkg/manifest/manifest.go

**WHAT**
- Add new field "phase" to Rules Engine in manifest.json structure;
- Add "phase" to azion.json as well;
- Add `--skip-build` flag to deploy command;
- Update manifest.json tests;

feat: add phase to manifest

---

pkg/manifest/manifest.go

**WHAT**
- Message showing rules being created and updated;

chore: show rules being updated/created

---

.goreleaser.yaml
pkg/cmd/whoami/whoami.go
pkg/cmd/whoami/whoami_test.go

**WHAT**
- Add unit tests to `whoami` command;
- Update `.goreleaser` to include tests subsection;

tests: add tests to whoami command

---

pkg/cmd/reset/reset.go
pkg/cmd/reset/reset_test.go

**WHAT**
- Update reset command structure
- Add unit tests

chore: add reset command unit tests

---

pkg/cmd/logout/logout.go
pkg/cmd/logout/logout_test.go

**WHAT**
- Update logout command structure
- Add unit tests

tests: add unit tests for logout command

---

pkg/cmd/root/pre_command.go
pkg/logger/logger.go
pkg/logger/logger_test.go

**WHAT**
- Delete logger functions no longer being used;
- Add more unit tests;

tests: add unit tests for logger package

---

pkg/cmd/link/link.go

Example to test: 
- `azion link --auto --mode html --preset deliver --format json`
- `azion link --remote https://github.com/maxwelbm/oldskool-html-bootstrap.git --auto --mode html --preset deliver --format json`

feat: output link

---

pkg/cmd/build/utils.go

Example to test:
- `azion build --format json`

feat: output build

---

pkg/cmd/init/init.go
pkg/cmd/link/link.go
pkg/cmd/root/pre_command.go
pkg/github/github.go
pkg/github/github_test.go
pkg/metric/count.go

**WHAT**
- New structure for github package;
- Update code to use new structure;
- Unit tests for github package;

tests: add unit tests for github package

---

pkg/cmd/delete/edge_application/edge_application.go
pkg/cmd/delete/edge_application/edge_application_test.go

**WHAT**
- Add tests to `updateAzionJson`;

tests: increase delete edge-application tests

---

messages/deploy/messages.go
messages/sync/messages.go
pkg/cmd/deploy/deploy.go
pkg/cmd/sync/sync.go
pkg/cmd/sync/tasks.go
pkg/github/github_test.go

**WHAT**
- Add .env sync to sync command;
- Add env flag to deploy command;

feat: sync .env file

---

pkg/cmd/init/init.go
pkg/cmd/link/link.go
pkg/node/node.go
pkg/node/node_test.go

**WHAT**
- Refactor node package;
- Add unit tests to node package;
- Update init/link to use new structure;

tests: add unit tests for the node package

---

pkg/cmd/build/vulcan.go
pkg/cmd/init/utils.go
pkg/cmd/link/utils.go
pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

**WHAT**
- Refactor to vulcan command;
- Refactor code that used vulcan structure;
- Add unit tests to vulcan package;

tests: add unit tests for the vulcan package

---

pkg/config/config_test.go

**WHAT**
- Add unit tests for the config package;

tests: add unit tests for the config package

---

pkg/cmd/list/cache_setting/cache_setting.go
pkg/cmd/list/domain/domain.go
pkg/cmd/list/edge_applications/edge_applications.go
pkg/cmd/list/edge_function/edge_function.go
pkg/cmd/list/edge_storage/object.go
pkg/cmd/list/origin/origin.go
pkg/cmd/list/personal_token/personal_token.go
pkg/cmd/list/rule_engine/rule_engine.go
pkg/cmd/list/variables/variables.go

**WHAT**
- Check for details to organize format in output;

fix: correct format fields

---

pkg/cmd/describe/cache_setting/cache_setting.go
pkg/cmd/describe/cache_setting/cache_setting_test.go
pkg/cmd/describe/domains/domains.go
pkg/cmd/describe/edge_applications/edge_applications.go
pkg/cmd/describe/edge_applications/edge_applications_test.go
pkg/cmd/describe/edge_function/edge_function.go
pkg/cmd/describe/edge_function/edge_function_test.go
pkg/cmd/describe/edge_storage/object_test.go
pkg/cmd/describe/origin/origin.go
pkg/cmd/describe/origin/origin_test.go
pkg/cmd/describe/personal_token/personal_token.go
pkg/cmd/describe/personal_token/personal_token_test.go
pkg/cmd/describe/rules_engine/rules_engine.go
pkg/cmd/describe/rules_engine/rules_engine_test.go
pkg/cmd/describe/variables/variables.go
pkg/cmd/describe/variables/variables_test.go

**WHAT**
- Improve unit tests for describe commands;
- Improve structures for describe commands;

tests: improve unit tests for describe commands

---

pkg/cmd/delete/edge_storage/bucket/bucket.go
pkg/cmd/purge/fixtures/response.json
pkg/cmd/purge/purge.go
pkg/cmd/purge/purge_test.go
pkg/cmd/purge/requests.go

**WHAT**
- Add unit tests for the purge command;
- Small refactor to the command;

tests: add unit tests for the purge command

---

pkg/cmd/sync/tasks.go
pkg/manifest/manifest.go

**WHAT**
- Add name of resource to error messages;
- Add phase to sync rules;
- Error reading .env file does not stop the execution;

chore: improve sync and manifest deploy

---

.goreleaser.yaml
pkg/cmd/dev/dev.go
pkg/cmd/dev/dev_test.go
pkg/cmd/dev/vulcan.go
pkg/cmd/sync/sync_test.go
utils/helpers.go

**WHAT**
- Add unit tests for the dev command;
- Minor refactor;

tests: add unit tests for the dev command

---

pkg/cmd/create/edge_function/edge_function.go
pkg/cmd/create/edge_storage/bucket.go
pkg/cmd/create/origin/origin.go
pkg/cmd/update/edge_storage/bucket.go
utils/helpers.go
utils/helpers_test.go

``` ok  	github.com/aziontech/azion-cli/utils	0.372s	coverage: 83.4% of statements ```

test: utils

---

pkg/manifest/manifest.go

**WHAT**
- Generating the error message would panic if structure was nil;

fix: error message would cause panic

---

pkg/cmd/create/edge_applications/edge_application.go
pkg/cmd/init/contracts.go
pkg/cmd/init/init.go
pkg/cmd/init/template.go
pkg/cmd/init/utils.go
pkg/cmd/link/link.go
pkg/cmd/link/utils.go
pkg/vulcan/vulcan.go

**WHAT**
- New init functionality:
- Vulcan no longer creates the templates; Azion CLI clones the samples repository and copies the correct folder to working directory;

chore: init command now clones template

---

pkg/vulcan/vulcan.go

**WHAT**
- Pin vulcan version to 3.0.0;

chore: pin vulcan version #patch

---

pkg/cmd/logs/cells/cells.go
pkg/cmd/logs/cells/cells_test.go
pkg/cmd/logs/http/http.go
pkg/cmd/logs/http/http_test.go

**WHAT**
- Refactor logs commands to use command factory;
- Add unit tests;

test: add unit tests for the log commands

---

messages/manifest/errors.go
messages/manifest/messages.go
pkg/cmd/deploy/deploy.go
pkg/contracts/contracts.go
pkg/manifest/manifest.go
pkg/manifest/request.go
pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

**WHAT**
- Add domain management through IaC;
- Add more options to origin management through IaC;
- Add purge management through IaC;

feat: add domain and purge management through azion.config to CLI

---

pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

- chore: vulcan fixed a problem with default value for origin path;

chore: update vulcan version

---

messages/deploy/messages.go
messages/dryrun/messages.go
pkg/cmd/deploy/deploy.go
pkg/cmd/deploy/requests.go
pkg/dry_run/dryrun.go
pkg/dry_run/dryrun_test.go

- Add dry-run flag to deploy command;

feat: add dry-run flag for the deploy command

---

cmd/azion/main.go
pkg/api/cache_setting/client.go
pkg/api/domain/domain.go
pkg/api/edge_applications/client.go
pkg/api/edge_function/client.go
pkg/api/origin/origin.go
pkg/api/personal_token/client.go
pkg/api/realtime_purge/realtime_purge.go
pkg/api/rules_engine/client.go
pkg/api/variables/client.go
pkg/cmd/root/root_test.go

chore: increase hard-coded timeout for http calls

---

pkg/cmd/deploy/deploy.go
pkg/contracts/contracts.go

- If --debug flag is sent, we show deploy logs locally;

feat: add logs to debug flag during deploy

---

messages/deploy/messages.go
messages/init/messages.go
messages/link/messages.go
pkg/cmd/deploy/deploy.go
pkg/cmd/deploy_remote/deploy.go
pkg/cmd/init/init.go
pkg/cmd/link/link.go
pkg/cmd/root/root.go

**WHAT**
- `--local` flag, allows for the entire build and deploy process to run locally;

feat: allow local deploy with flag

---

messages/dev/messages.go
pkg/cmd/dev/dev.go
pkg/cmd/dev/vulcan.go

Add the flag `--port`, which allows user to define which port to start localhost at;

feat: new flag --port in dev command

---

messages/sync/messages.go
pkg/cmd/sync/tasks.go

- When running sync command, we now update remote variables if they are found in local .env file;

feat: update remote env vars

---

messages/init/messages.go
pkg/cmd/init/init.go

- Add spinner while fetching template in init command;

feat: add spinner while fetching template

---

messages/sync/messages.go
messages/variables/messages.go
pkg/cmd/create/variables/variables.go
pkg/cmd/sync/tasks.go
utils/helpers.go

**WHAT**
- If any of the following words is used, the variable becomes a secret: 
- `"PASSWORD", "PWD", "SECRET", "HASH", "ENCRYPTED", "PASSCODE", "AUTH", "TOKEN", "SECRET"`

chore: make variables secret if a certain word is used

---

pkg/cmd/create/create.go
pkg/cmd/delete/delete.go
pkg/cmd/describe/describe.go
pkg/cmd/list/list.go
pkg/cmd/update/update.go

- Update CRUD examples for subcommands;

chore: update CRUD examples

---

.github/workflows/deploy_prod.yml
chocolatey/azion.nuspec
chocolatey/tools/chocolateyinstall.ps1
chocolatey/tools/chocolateyuninstall.ps1

- Publish CLI to chocolatey package manager;

feat: publish CLI to chocolatey package manager

---

.github/workflows/deploy_prod.yml
.goreleaser.yaml

**WHAT**
- Publish Azion CLI to Winget (Windows Package Manager);

feat: publish CLI to Windows Package Manager

---

.github/workflows/deploy_prod.yml
cmd/azion/main.go
messages/root/errors.go
messages/root/messages.go
pkg/cmd/root/pre_command.go
pkg/cmd/root/root.go

- Timeout flag which sets maximum time before the CLI times out during an HTTP call (default value: 50 seconds);

feat: add timeout global flag

---

messages/deploy-remote/messages.go
messages/deploy/messages.go

Simplifies the message about creating Cache Settings on the `deploy` command.

[EDU-5575] Improve create cache settings message on deploy

---

.github/workflows/deploy_prod.yml
README.md

- Used `komac` to publish on winget

chore: update winget publish

---

pkg/vulcan/vulcan.go
pkg/vulcan/vulcan_test.go

- Updating version that fixed a bug;

chore: update bundler version

---

pkg/cmd/rollback/rollback.go
utils/helpers.go

chore: remove println

---

pkg/github/github.go
pkg/github/github_test.go

- Add `.open-next `folder to gitignore during link.

chore: add open-next to gitignore

---

env/prod
pkg/v3commands/deploy/deploy.go
pkg/v3commands/deploy/deploy_test.go
pkg/v3commands/deploy/scriptrunner.go
pkg/v3commands/deploy/upload.go
pkg/v3commands/deploy/zip.go
pkg/v3commands/link/link.go

- Add missing variable to remote deploy
- Uncomment s3 credential variables

Deploy to Production - 2025/08/22
